# action1:
#   type: "app"
#   name: "Notepad++"
#   path: 'C:\Programy\Notepad++\notepad++.exe'

# action2:
#   type: "sleep"
#   value: 1

# action3:
#   type: "keystroke"
#   flow: ""
#   sequence:
#     - ["ctrl", "A"]

action4:
  type: "app"
  name: "Chrome - PZMedia"
  path: 'C:\"Program Files"\Google\Chrome\Application\chrome.exe "http://192.168.1.18:8829"'

action5:
  type: "sleep"
  value: 5

action6:
  type: "keystroke"
  sequence:
    - "Dupa biskupa"
